const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={type:'feed',media:[],posts:[],month:new Date(),api:true};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Erro no servidor');return d}
async function loadPosts(){try{state.posts=await api('/api/posts');state.api=true}catch{state.api=false;state.posts=JSON.parse(localStorage.getItem('jb_posts')||'[]')}renderAll()}
function saveLocal(){localStorage.setItem('jb_posts',JSON.stringify(state.posts));renderAll()}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent=({dashboard:'Dashboard',calendar:'Calendário',create:'Criar publicação',library:'Biblioteca'})[name]||'';}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#newPostBtn').onclick=()=>showView('create');
$$('#typeTabs button').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;$$('#typeTabs button').forEach(x=>x.classList.toggle('active',x===b));$('#pollBox').classList.toggle('hidden',state.type!=='story');updatePreview()});
['caption','hashtags','pollQuestion','pollA','pollB'].forEach(id=>$('#'+id).addEventListener('input',updatePreview));
$('#pollEnabled').addEventListener('change',updatePreview);
$('#mediaInput').addEventListener('change',e=>{[...e.target.files].forEach(file=>{const url=URL.createObjectURL(file);state.media.push({url,type:file.type,name:file.name,file});});renderMedia();updatePreview();renderLibrary()});
function renderMedia(){const s=$('#mediaStrip');s.innerHTML='';state.media.forEach((m,i)=>{const wrap=document.createElement('div');wrap.className='media-thumb-wrap';const el=document.createElement(m.type.startsWith('video')?'video':'img');el.src=m.url;el.className='media-thumb';if(el.tagName==='VIDEO')el.muted=true;const x=document.createElement('button');x.className='remove-media';x.textContent='×';x.onclick=()=>{state.media.splice(i,1);renderMedia();updatePreview();renderLibrary()};wrap.append(el,x);s.append(wrap)})}
function updatePreview(){const media=$('#previewMedia');media.innerHTML='';if(state.media[0]){const m=state.media[0],el=document.createElement(m.type.startsWith('video')?'video':'img');el.src=m.url;if(el.tagName==='VIDEO'){el.controls=true;el.muted=true}media.append(el)}else media.innerHTML='<span>Sua mídia aparecerá aqui</span>';$('#previewCaption').textContent=$('#caption').value||'Sua legenda...';$('#previewHashtags').textContent=$('#hashtags').value||'';const isStory=state.type==='story';$('#phonePreview').classList.toggle('story-preview',isStory);const poll=isStory&&$('#pollEnabled').checked;$('#previewPoll').classList.toggle('hidden',!poll);$('#previewPollQuestion').textContent=$('#pollQuestion').value||'Qual você escolheria hoje?';$('#previewPollA').textContent=$('#pollA').value||'Opção A';$('#previewPollB').textContent=$('#pollB').value||'Opção B';}
function readFileDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function uploadMedia(){if(!state.api)return state.media.map(m=>({name:m.name,type:m.type}));const out=[];for(const m of state.media){if(m.serverUrl){out.push(m);continue}const dataUrl=await readFileDataURL(m.file);out.push(await api('/api/media',{method:'POST',body:JSON.stringify({name:m.name,type:m.type,dataUrl})}))}return out}
async function buildPost(){const date=$('#postDate').value,time=$('#postTime').value,status=$('#postStatus').value;if(!date){toast('Escolha uma data.');return null}if(!state.media.length&&status==='Agendado'){toast('Adicione uma foto ou vídeo.');return null}const media=await uploadMedia();return{type:state.type,caption:$('#caption').value,hashtags:$('#hashtags').value,location:$('#location').value,link:$('#link').value,date,time,status,pollEnabled:$('#pollEnabled').checked,pollQuestion:$('#pollQuestion').value,pollA:$('#pollA').value,pollB:$('#pollB').value,media}}
async function createPost(){try{const p=await buildPost();if(!p)return;if(state.api){const saved=await api('/api/posts',{method:'POST',body:JSON.stringify(p)});state.posts.unshift(saved)}else{p.id=Date.now();state.posts.unshift(p);saveLocal()}renderAll();toast('Publicação salva.');showView('calendar')}catch(e){toast(e.message)}}
$('#savePost').onclick=createPost;
$('#clearForm').onclick=()=>{state.media=[];renderMedia();['caption','location','link','pollQuestion','pollA','pollB'].forEach(id=>$('#'+id).value='');$('#hashtags').value='#juniorburgeroficial';$('#pollEnabled').checked=false;updatePreview()};
function labelType(t){return({feed:'Feed',carousel:'Carrossel',story:'Story',reel:'Reel'})[t]||t}
function fmtDate(d){if(!d)return'';const [y,m,day]=d.split('-');return `${day}/${m}/${y}`}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderDashboard(){const groups={Agendado:0,Rascunho:0,Publicado:0,Erro:0};state.posts.forEach(p=>groups[p.status]=(groups[p.status]||0)+1);$('#statScheduled').textContent=groups.Agendado||0;$('#statDrafts').textContent=groups.Rascunho||0;$('#statPublished').textContent=groups.Publicado||0;$('#statErrors').textContent=groups.Erro||0;const list=$('#upcomingList');const sorted=[...state.posts].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,10);list.classList.toggle('empty-state',!sorted.length);list.innerHTML=sorted.length?'':'Nenhuma publicação agendada.';sorted.forEach(p=>{const d=document.createElement('div');d.className='post-row';d.innerHTML=`<div><strong>${labelType(p.type)} • ${escapeHtml(p.status||'')}</strong><small>${fmtDate(p.date)} ${p.time||''}</small><p>${escapeHtml((p.caption||'Sem legenda').slice(0,80))}</p></div><div class="row-actions"><button data-pub="${p.id}">Publicar</button><button data-del="${p.id}">Excluir</button></div>`;list.append(d)});$$('[data-del]').forEach(b=>b.onclick=()=>deletePost(b.dataset.del));$$('[data-pub]').forEach(b=>b.onclick=()=>publishNow(b.dataset.pub))}
async function deletePost(id){try{if(state.api)await api('/api/posts/'+encodeURIComponent(id),{method:'DELETE'});state.posts=state.posts.filter(p=>String(p.id)!==String(id));if(!state.api)saveLocal();renderAll();toast('Post excluído.')}catch(e){toast(e.message)}}
async function publishNow(id){if(!state.api)return toast('Abra pelo servidor para publicar.');try{toast('Enviando para o Instagram...');await api(`/api/posts/${encodeURIComponent(id)}/publish`,{method:'POST'});await loadPosts();toast('Publicado com sucesso.')}catch(e){await loadPosts();toast(e.message)}}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth();$('#calendarTitle').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(state.month);const grid=$('#calendarGrid');grid.innerHTML='';['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].forEach(w=>{const h=document.createElement('div');h.className='weekday';h.textContent=w;grid.append(h)});const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const cell=document.createElement('div');cell.className='cal-cell'+(d.getMonth()!==m?' muted-day':'');cell.innerHTML=`<div class="cal-day">${d.getDate()}</div>`;state.posts.filter(p=>p.date===iso).forEach(p=>{const e=document.createElement('div');e.className='event '+p.type;e.textContent=`${p.time||''} ${labelType(p.type)}`;cell.append(e)});grid.append(cell)}}
$('#prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};
$('#nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};
function renderLibrary(){const g=$('#libraryGrid');g.innerHTML='';const all=state.posts.flatMap(p=>p.media||[]);if(!all.length){g.classList.add('empty-state');g.innerHTML='As mídias dos seus posts aparecerão aqui.';return}g.classList.remove('empty-state');all.forEach(m=>{const el=document.createElement(m.type?.startsWith('video')?'video':'img');el.src=m.serverUrl||m.url||'';if(el.tagName==='VIDEO'){el.controls=true;el.muted=true}g.append(el)})}
async function refreshMetaStatus(){if(!state.api){$('#instagramStatus').textContent='Servidor offline';return}try{const s=await api('/api/meta/status');$('#instagramStatus').textContent=s.connected?`Conectado${s.username?' @'+s.username:''}`:(s.configured?'Pronto para conectar':'Falta configurar Meta');$('#instagramButton').textContent=s.connected?'Reconectar Instagram':'Conectar Instagram'}catch(e){$('#instagramStatus').textContent=e.message}}
$('#instagramButton').onclick=async()=>{if(!state.api)return toast('Abra pelo servidor.');try{const d=await api('/api/meta/connect');location.href=d.url}catch(e){toast(e.message)}};
function setToday(){const d=new Date(),iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;$('#postDate').value=iso}
function renderAll(){renderDashboard();renderCalendar();renderLibrary();updatePreview()}
setToday();loadPosts();refreshMetaStatus();if(new URLSearchParams(location.search).get('instagram')==='connected'){toast('Instagram conectado com sucesso.');history.replaceState({},'',location.pathname)}
